env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "bZD2u6cC07YuPSDMa92Df5sb409+StAV0Y/wsM4hfJSGZd9Tg/On4N8IPKNj8g6XGTI3ewFFuVz41PJNUOtLK0H0gqCAUPcgIiUqtGDewqEh38yhyU/+uIoKRxhQEAYEL+IysnROkghQlrNDRsmLZMLsTARhExxE4cO9HsCPZDSTN2JPiJoVKKzOZaq0+rOsxjPBaJPJ8vSXP5oRk8/I8Lt8nvQ9R8szS7ChiNY1iRRQ/JxEwGi4J7EH7gU/0ReWM2IDMSPt8NpweQKH1pD27hWDWO+eIH2CjOW5em0JBpnmPV++BvDGyMAXPnJD5xSPT1EVHTHjI7khc/RnChf7lfa8EodubzCni2eJPzwUYxcl3S5MwADCmvpsLZhhlpSpVztg9dPLr+cW7chbHnR1PlYMNJ+K2vwuTMTcBc3XRTWKvgEkkQrLWhodKTDTv8luR//Y4MERj6gkvGWN4q6vv/VDAVUUlr+h+V5CH1UiWvyR7rBxrAjTd/4bwHh6PDzgdaGTvXlonN8jmQL0wi1g0x8gMEPcxneKuRdtvWQviQerwpVJJyrewDGxfN/EjeyqqAzz3AkuESQgkvkSoK7YNGCRxaFVSrhpTkaThsLfc44JvZtJEaHQAGzizYn66cl4OBQXk0Zpz+XA5hD+cF0kkeotWK3LcetisePaWJf6uGs="

sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "pypy"
      env: TOXENV=pypy
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "2.7"
      env: TOXENV=pep8
    - python: "3.5"
      env: TOXENV=pep8py3
  allow_failures:
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "pypy3"
      env: TOXENV=pypy3


install:
  - pip install tox

script:
  - tox

addons:
  coverity_scan:
    project:
      name: "tiran/pysha3"
      description: "Build submitted via Travis CI"
    notification_email: christian@python.org
    build_command_prepend: "make clean"
    build_command: "make test"
    branch_pattern: coverity_scan

